// import styles from "./PartyScreen.module.css";

export default function PartyScreen() {
  return (
    <div>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
      <p>This is the Party Screen</p>
    </div>
  );
}
